apiVersion: apps/v1
kind: Deployment
metadata:
  name: shligga
spec:
  replicas: 1
  selector:
    matchLabels:
      version: 2.0.0
  template:
    metadata:
      labels:
        version: 2.0.0
    spec:
      containers:
        - name: shligga
          image: nginxinc/nginx-unprivileged:stable
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data

      volumes:
        - name: es-data
          emptyDir: {}
