apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tomerkenis-dev
  name: porygon-deployment-editor
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "update"]
